version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'yeya'
      MYSQL_USER: 'yeya'
      MYSQL_PASSWORD: 'yeya'
      MYSQL_ROOT_PASSWORD: '1546'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db
  backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    restart: always
volumes:
  my-db:
